"""Initial migration

Revision ID: de7748b8d78e
Revises: 
Create Date: 2024-12-19 09:16:57.073066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7748b8d78e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('price_threshold', sa.Float(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_alerts_id'), 'crypto_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_alerts_symbol'), 'crypto_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_crypto_alerts_user_id'), 'crypto_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_alerts_user_id'), table_name='crypto_alerts')
    op.drop_index(op.f('ix_crypto_alerts_symbol'), table_name='crypto_alerts')
    op.drop_index(op.f('ix_crypto_alerts_id'), table_name='crypto_alerts')
    op.drop_table('crypto_alerts')
    # ### end Alembic commands ###
